# This is a schema configuration for grano. 
# For more details on what this does and how it works, see: 


# System core schemata

  - name: base
    label: Common for all entities.
    obj: entity
    attributes:
      - name: name
        label: Name
      - name: tagline
        label: Short description


# Common schemata

  - name: public_body
    label: Public body
    obj: entity
    attributes: []


  - name: organisation
    label: "Company, NGO or public institution"
    obj: entity
    attributes:
      - name: acronym
        label: Acronym


  - name: address
    label: Address
    obj: entity
    attributes:
      - name: street
        label: Street
      - name: city
        label: City
      - name: postcode
        label: Postal code
      - name: country
        label: Country
      - name: country_code
        label: "Country Code (ISO 3166-2)"



  - name: geolocated
    label: Geo-located entity
    obj: entity
    attributes:
      - name: lon
        label: Longitude
      - name: lat
        label: Latitude
      - name: nuts1
        label: NUTS1 Code
      - name: nuts1_label
        label: NUTS1 Name
      - name: nuts2
        label: NUTS2 Code
      - name: nuts2_label
        label: NUTS2 Name
      - name: nuts3
        label: NUTS3 Code



# FTS - EC Financial Transparency System 

  - name: fts_committment
    label: "EC Financial Transparency System: Committment"
    obj: relation
    attributes:
      - name: amount
        label: Amount (in this committment)
      - name: total
        label: Amount (total)
      - name: article
        label: Article (EU budget)
      - name: item
        label: Item (EU budget)
      - name: title
        label: Title (EU budget)
      - name: chapter
        label: Chapter (EU budget)
      - name: budget_code
        label: EU budget code
      - name: budget_item
        label: EU budget item
      - name: cofinancing_rate
        label: Co-financing rate (text)
      - name: cofinancing_rate_pct
        label: Co-financing rate (numeric)
      - name: date
        label: Year
      - name: grant_subject
        label: Grant subject
      - name: position_key
        label: Position key
      - name: action_type
        label: Action Type
      - name: coordinator
        label: Coordinator
